name: Rubocop

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Rubocop Linter
        uses: gannagoodkevich/OOP_rails
        with:
          ruby-version: 2.6.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}